pipeline {
    agent any
    environment {
        // Path to your Docker Compose file
        COMPOSE_FILE = "${WORKSPACE}/infrastructure/docker-compose.yml"
    }
    stages {
                stage('Update darcom OS Packages') {
                    steps {
                        sshagent(['darcom-ssh']) {
                            sh 'ssh -o StrictHostKeyChecking=no dar@darcom "sudo apt-get update && sudo apt-get -y upgrade"'
                        }
                    }
                }
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Pull Latest Images') {
            steps {
                sh 'docker compose -f $COMPOSE_FILE pull'
            }
        }
        stage('Deploy Services') {
            steps {
                sh 'docker compose -f $COMPOSE_FILE up -d'
            }
        }
        stage('Cleanup') {
            steps {
                sh 'docker image prune -f'
            }
        }
    }
    post {
        success {
            echo 'Services updated and running!'
        }
        failure {
            echo 'Deployment failed. Check logs.'
        }
    }
}
